apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acs-operator-subscription
  namespace: stackrox
spec:
  channel: "stable"
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
